name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Create tsconfig.json
        run: echo '{"compilerOptions":{"target":"es6","module":"commonjs","outDir":"build","strict":true}}' > tsconfig.json

      - name: Build
        run: npm run build

      - name: Install jest globally
        run: npm install -g jest

      - name: Run tests
        run: npm test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public